import { useEffect, useMemo, useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { AlertCircle, ArrowLeft, ArrowRight, CalendarDays, Check, ChevronDown, ChevronUp, Clock3, Heart, MessageCircle, PawPrint, Plus, RotateCcw, ShieldCheck, Upload, X } from 'lucide-react'
import { services } from './data'
import { api } from './api'
import { useAuth } from './auth-context'

const KEY='realengo-booking-draft-v2', TTL=86400000
const newPet=(service='')=>({id:crypto.randomUUID(),accountPetId:null,name:'',species:'Perro',breed:'',size:'',age:'',photoName:'',services:service?[service]:[],allergies:'',conditions:'',skin:'',specialNeeds:'',vaccination:'Por indicar',behavior:'',notes:''})
const newCustomer={name:'',phone:'',whatsapp:'',email:'',contactMethod:'WhatsApp'}
const stepData=[['Tu mascota','Cuéntanos sobre tu mascota'],['Servicios','Elige todo lo que necesita'],['Información','Ayúdanos a cuidarla mejor'],['Fecha y hora','Escoge el mejor momento'],['Tus datos','Ya casi terminamos'],['Confirmar','Revisaremos cada detalle']]
const slots=['9:00 a. m.','10:30 a. m.','12:00 p. m.','2:30 p. m.','4:00 p. m.']
const readDraft=()=>{try{const x=JSON.parse(localStorage.getItem(KEY));if(!x||Date.now()-x.savedAt>TTL){localStorage.removeItem(KEY);return null}return{...x.data,pets:x.data.pets.map(p=>({...p,allergies:'',conditions:'',skin:'',specialNeeds:'',behavior:'',notes:''}))}}catch{return null}}

export default function BookingExperience(){
 const {user}=useAuth()
 const initial=new URLSearchParams(useLocation().search).get('servicio')||'', restored=useMemo(readDraft,[])
 const [step,setStep]=useState(restored?.step||0),[pets,setPets]=useState(restored?.pets||[newPet(initial)]),[activeId,setActiveId]=useState(restored?.activeId||restored?.pets?.[0]?.id||null)
 const [appointment,setAppointment]=useState(restored?.appointment||{date:'',time:''}),[customer,setCustomer]=useState(restored?.customer||newCustomer),[errors,setErrors]=useState({}),[consent,setConsent]=useState(false),[success,setSuccess]=useState(null),[loading,setLoading]=useState(false),[mobileOpen,setMobileOpen]=useState(false),[savedPets,setSavedPets]=useState([])
 const active=pets.find(p=>p.id===activeId)||pets[0], updatePet=patch=>setPets(v=>v.map(p=>p.id===active.id?{...p,...patch}:p))
 useEffect(()=>{if(user)api('/api/pets').then(data=>setSavedPets(data.pets)).catch(()=>setSavedPets([]));else setSavedPets([])},[user])
 useEffect(()=>{if(user)setCustomer(current=>({...current,name:current.name||user.name,phone:current.phone||user.phone||'',whatsapp:current.whatsapp||user.whatsapp||'',email:current.email||user.email,contactMethod:user.preferredContact||current.contactMethod}))},[user])
 useEffect(()=>{if(!success){const safePets=pets.map(p=>({id:p.id,accountPetId:p.accountPetId,name:p.name,species:p.species,breed:p.breed,size:p.size,age:p.age,photoName:'',services:p.services,vaccination:p.vaccination}));localStorage.setItem(KEY,JSON.stringify({savedAt:Date.now(),data:{step,pets:safePets,activeId:active.id,appointment,customer}}))}},[step,pets,active,appointment,customer,success])
 const validate=()=>{const e={};if(step===0)pets.forEach(p=>{if(!p.name)e[`name-${p.id}`]='Escribe el nombre de esta mascota.'});if(step===1&&pets.some(p=>!p.services.length))e.services='Cada mascota necesita al menos un servicio.';if(step===3){if(!appointment.date)e.date='Selecciona una fecha.';if(!appointment.time)e.time='Selecciona un horario.'}if(step===4){if(!customer.name)e.customerName='Escribe tu nombre.';if(!customer.phone)e.phone='Escribe un teléfono.';if(!customer.email)e.email='Escribe un correo.';else if(!/^\S+@\S+\.\S+$/.test(customer.email))e.email='Escribe un correo válido.'}if(step===5&&!consent)e.consent='Debes aceptar antes de enviar.';setErrors(e);return !Object.keys(e).length}
 const goNext=()=>{if(validate()){setErrors({});setStep(s=>Math.min(5,s+1));window.scrollTo({top:0,behavior:'smooth'})}}, reset=()=>{if(!window.confirm('¿Borrar el borrador y comenzar de nuevo?'))return;localStorage.removeItem(KEY);const p=newPet(initial);setPets([p]);setActiveId(p.id);setAppointment({date:'',time:''});setCustomer(newCustomer);setStep(0);setSuccess(null);setConsent(false)}
 const addPet=()=>{const p=newPet();setPets(v=>[...v,p]);setActiveId(p.id);setStep(0)}, removePet=id=>{if(pets.length===1)return;const v=pets.filter(p=>p.id!==id);setPets(v);if(id===active.id)setActiveId(v[0].id)}
 const submit=async()=>{if(!validate()||loading)return;if(!user){setErrors({account:'Inicia sesión o crea una cuenta para guardar esta solicitud definitivamente.'});return}setLoading(true);setErrors({});try{const catalog=await api('/api/catalog/services');const serviceMap=new Map(catalog.services.map(s=>[s.slug,s.id]));const persisted=[];for(const pet of pets){if(pet.accountPetId){persisted.push({...pet,petId:pet.accountPetId});continue}const created=await api('/api/pets',{method:'POST',body:{name:pet.name,species:pet.species,breed:pet.breed||null,ageLabel:pet.age||null,notes:pet.notes||null,allergies:pet.allergies||null,conditions:pet.conditions||null}});persisted.push({...pet,petId:created.pet.id})}const time24={'9:00 a. m.':'09:00','10:30 a. m.':'10:30','12:00 p. m.':'12:00','2:30 p. m.':'14:30','4:00 p. m.':'16:00'}[appointment.time];const result=await api('/api/appointments',{method:'POST',body:{requestedAt:new Date(`${appointment.date}T${time24}:00`).toISOString(),notes:null,pets:persisted.map(p=>({petId:p.petId,serviceIds:p.services.map(slug=>serviceMap.get(slug)).filter(Boolean)}))}});setSuccess({request:result.requestGroupId,pets,appointment,customer:{...customer,name:user.name,phone:user.phone||customer.phone,email:user.email,contactMethod:user.preferredContact}});localStorage.removeItem(KEY)}catch(error){setErrors({submit:error.message})}finally{setLoading(false)}}
 if(success)return <BookingSuccess data={success} onNew={reset}/>
 return <><section className="booking-hero"><div className="shell"><span className="eyebrow">Solicitud de cita · {user?'Cuenta conectada':'Borrador temporal'}</span><h1>{stepData[step][1]}</h1><p>Personaliza el cuidado de {active?.name||'tu mascota'} con calma. La solicitud quedará pendiente de confirmación.</p></div></section>{restored&&<div className="draft-notice shell"><RotateCcw/><span><b>Recuperamos tu progreso.</b> El borrador expira después de 24 horas y no conserva información médica.</span><button onClick={reset}>Borrar y comenzar de nuevo</button></div>}<main className="booking-shell shell"><div className="booking-main"><BookingStepper step={step} setStep={setStep}/><section className="booking-panel" aria-live="polite">{step===0&&<PetForm pets={pets} active={active} setActiveId={setActiveId} updatePet={updatePet} addPet={addPet} removePet={removePet} errors={errors} savedPets={savedPets}/>} {step===1&&<ServiceSelector pets={pets} active={active} setActiveId={setActiveId} updatePet={updatePet} errors={errors}/>} {step===2&&<HealthForm active={active} updatePet={updatePet}/>} {step===3&&<AppointmentCalendar appointment={appointment} setAppointment={setAppointment} errors={errors}/>} {step===4&&<CustomerForm customer={customer} setCustomer={setCustomer} errors={errors}/>} {step===5&&<BookingReview pets={pets} appointment={appointment} customer={customer} consent={consent} setConsent={setConsent} errors={errors}/>} {step===5&&!user&&<p className="booking-account-gate"><ShieldCheck/> Para enviar y consultar esta solicitud, <Link to="/mi-cuenta">inicia sesión o crea una cuenta</Link>. Tu borrador temporal permanecerá disponible durante 24 horas.</p>}{errors.submit&&<p className="field-error" role="alert">{errors.submit}</p>}{errors.account&&<p className="field-error" role="alert">{errors.account}</p>}<div className="booking-actions"><button className="btn btn-ghost" disabled={step===0} onClick={()=>setStep(s=>Math.max(0,s-1))}><ArrowLeft/> Anterior</button>{step<5?<button className="btn btn-primary" onClick={goNext}>Continuar <ArrowRight/></button>:<button className="btn btn-primary" disabled={loading||!user} onClick={submit}>{loading?'Guardando…':user?'Enviar solicitud pendiente':'Inicia sesión para enviar'}</button>}</div></section></div><SelectedServicesSummary pets={pets} appointment={appointment}/></main><MobileBookingSummary pets={pets} appointment={appointment} open={mobileOpen} setOpen={setMobileOpen}/></>
}

export function BookingStepper({step,setStep}){return <nav className="booking-stepper" aria-label="Progreso de reserva"><div className="progress-copy"><span>Paso {step+1} de 6</span><b>{stepData[step][0]}</b></div><div className="progress-track"><i style={{width:`${((step+1)/6)*100}%`}}/></div><ol>{stepData.map(([label],i)=><li key={label} className={i===step?'current':i<step?'complete':''}><button onClick={()=>i<step&&setStep(i)} disabled={i>step} aria-current={i===step?'step':undefined}><span>{i<step?<Check/>:i+1}</span><b>{label}</b></button></li>)}</ol></nav>}
export function PetForm({pets,active,setActiveId,updatePet,addPet,removePet,errors,savedPets=[]}){return <div><Heading icon={<PawPrint/>} title="Queremos conocer a tu mascota" text="Cada mascota conservará sus propios datos y servicios."/>{savedPets.length>0&&<div className="saved-pet-picker"><span>Mascotas guardadas en tu cuenta</span><div>{savedPets.map(pet=><button key={pet.id} className={active.accountPetId===pet.id?'active':''} onClick={()=>updatePet({accountPetId:pet.id,name:pet.name,species:pet.species,breed:pet.breed||'',age:pet.ageLabel||'',allergies:pet.allergies||'',conditions:pet.conditions||'',notes:pet.notes||''})}><PawPrint/>{pet.name}</button>)}</div></div>}<PetSelector pets={pets} active={active} setActiveId={setActiveId} addPet={addPet} removePet={removePet}/><div className="form-grid pet-fields"><Field label="Nombre" value={active.name} change={v=>updatePet({name:v,accountPetId:null})} error={errors[`name-${active.id}`]} required/><label>Tipo de mascota<select value={active.species} onChange={e=>updatePet({species:e.target.value,accountPetId:null})}><option>Perro</option><option>Gato</option><option>Otra — consultar</option></select></label><Field label="Raza" value={active.breed} change={v=>updatePet({breed:v,accountPetId:null})} placeholder="Si la conoces"/><label>Tamaño o peso aproximado<select value={active.size} onChange={e=>updatePet({size:e.target.value})}><option value="">Seleccionar</option><option>Pequeño</option><option>Mediano</option><option>Grande</option><option>Peso por confirmar</option></select></label><Field label="Edad aproximada" value={active.age} change={v=>updatePet({age:v,accountPetId:null})} placeholder="Opcional"/><label className="photo-field"><span>Fotografía opcional</span><input type="file" accept="image/*" onChange={e=>updatePet({photoName:e.target.files?.[0]?.name||''})}/><i><Upload/>{active.photoName||'Elegir una foto'}</i><small>La carga privada requiere configurar el proveedor de almacenamiento.</small></label></div></div>}
export function PetSelector({pets,active,setActiveId,addPet,removePet}){return <div className="pet-tabs" role="tablist">{pets.map((p,i)=><div className={p.id===active.id?'active':''} key={p.id}><button role="tab" aria-selected={p.id===active.id} onClick={()=>setActiveId(p.id)}><PawPrint/>{p.name||`Mascota ${i+1}`}</button>{pets.length>1&&<button className="remove-pet" aria-label={`Eliminar ${p.name||'mascota'}`} onClick={()=>removePet(p.id)}><X/></button>}</div>)}<button className="add-pet" onClick={addPet}><Plus/> Agregar otra mascota</button></div>}
export function ServiceSelector({pets,active,setActiveId,updatePet,errors}){const [filter,setFilter]=useState('Todos'),cats={'bano-clasico-ozono':'Grooming','banos-medicados':'Piel','corte-comercial':'Grooming','cortes-por-raza':'Grooming','consulta-veterinaria':'Veterinaria','profilaxis-dental':'Veterinaria'},toggle=slug=>updatePet({services:active.services.includes(slug)?active.services.filter(x=>x!==slug):[...active.services,slug]});return <div><Heading icon={<Heart/>} title={`Plan de cuidado de ${active.name||'tu mascota'}`} text="Puedes elegir todos los servicios que necesite. Nada se agrega automáticamente."/><div className="pet-mini-tabs">{pets.map(p=><button className={p.id===active.id?'active':''} onClick={()=>setActiveId(p.id)} key={p.id}>{p.name||'Mascota'} <span>{p.services.length}</span></button>)}</div><div className="service-filters">{['Todos','Grooming','Piel','Veterinaria'].map(c=><button className={filter===c?'active':''} onClick={()=>setFilter(c)} key={c}>{c}</button>)}</div><div className="selection-grid">{services.filter(s=>filter==='Todos'||cats[s.slug]===filter).map(s=><ServiceSelectionCard key={s.slug} service={s} selected={active.services.includes(s.slug)} toggle={toggle}/>)}</div>{errors.services&&<p className="field-error" role="alert"><AlertCircle/>{errors.services}</p>}<Recommendation selected={active.services}/><PetCarePlan pet={active} toggle={toggle}/></div>}
export function ServiceSelectionCard({service,selected,toggle}){return <article className={`selection-card ${selected?'selected':''}`}><img src={service.image} alt=""/><div><span className="selection-status">{selected?<><Check/> Agregado</>:'Disponible'}</span><h3>{service.name}</h3><p>{service.short}</p><ul>{service.benefits.slice(0,2).map(x=><li key={x}><Check/>{x}</li>)}</ul><div className="selection-meta"><span>Precio por confirmar</span><span>Duración por confirmar</span></div><div className="selection-actions"><button className={`btn ${selected?'btn-ghost':'btn-primary'}`} aria-pressed={selected} onClick={()=>toggle(service.slug)}>{selected?<><X/> Quitar</>:<><Plus/> Agregar</>}</button><Link to={`/servicios/${service.slug}`}>Ver detalles</Link></div></div></article>}
function Recommendation({selected}){let text='';if(selected.includes('cortes-por-raza')&&!selected.includes('bano-clasico-ozono'))text='También puedes agregar un baño para completar el cuidado del pelaje.';if(selected.includes('banos-medicados'))text='El baño medicado debe confirmarse previamente con el personal según las necesidades de la piel.';if(selected.includes('profilaxis-dental')||selected.includes('consulta-veterinaria'))text='El equipo confirmará cualquier preparación necesaria antes de la cita.';return text?<div className="recommendation"><Heart/><div><b>Sugerencia para tu selección</b><p>{text}</p></div></div>:null}
export function PetCarePlan({pet,toggle}){return <section className="care-plan"><div><span className="eyebrow">Paquete personalizado</span><h3>Plan de cuidado de {pet.name||'tu mascota'}</h3></div><span className="care-count">{pet.services.length} servicios</span>{pet.services.length?<ul>{pet.services.map(slug=><li key={slug}><span>{services.find(s=>s.slug===slug)?.name}</span><button onClick={()=>toggle(slug)} aria-label="Quitar servicio"><X/></button></li>)}</ul>:<p>Aún no has agregado servicios.</p>}<div className="care-meta"><span><b>Precio</b> Por confirmar</span><span><b>Duración</b> Por confirmar</span></div><small>El precio y la duración final pueden variar según raza, tamaño, pelaje, condición y evaluación del personal.</small></section>}
export function HealthForm({active,updatePet}){return <div><Heading icon={<Heart/>} title={`Ayúdanos a cuidar mejor a ${active.name}`} text="Comparte solamente lo necesario. No realizamos diagnósticos automáticos."/><div className="form-grid"><Area label="Alergias conocidas" value={active.allergies} change={v=>updatePet({allergies:v})}/><Area label="Condiciones médicas relevantes" value={active.conditions} change={v=>updatePet({conditions:v})}/><Area label="Sensibilidad en la piel" value={active.skin} change={v=>updatePet({skin:v})}/><Area label="Discapacidad o necesidad especial" value={active.specialNeeds} change={v=>updatePet({specialNeeds:v})}/><label>Estado de vacunación<select value={active.vaccination} onChange={e=>updatePet({vaccination:e.target.value})}><option>Por indicar</option><option>Al día según el propietario</option><option>Pendiente de actualización</option><option>No aplica / consultar</option></select></label><Area label="Comportamiento relevante" value={active.behavior} change={v=>updatePet({behavior:v})}/><label className="full-field">Observaciones<textarea value={active.notes} onChange={e=>updatePet({notes:e.target.value})}/></label></div><p className="notice">No uses este formulario para emergencias. El borrador expira en 24 horas.</p></div>}
export function AppointmentCalendar({appointment,setAppointment,errors}){const dates=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i+1);return d});return <div><Heading icon={<CalendarDays/>} title="Escoge el mejor momento" text="La disponibilidad es demostrativa y requiere confirmación."/><div className="date-strip" role="group" aria-label="Fechas">{dates.map(d=>{const v=d.toISOString().slice(0,10);return <button className={appointment.date===v?'selected':''} aria-pressed={appointment.date===v} onClick={()=>setAppointment({...appointment,date:v,time:''})} key={v}><span>{d.toLocaleDateString('es-DO',{weekday:'short'})}</span><b>{d.getDate()}</b><small>{d.toLocaleDateString('es-DO',{month:'short'})}</small></button>})}</div>{errors.date&&<p className="field-error" role="alert">{errors.date}</p>}<h3 className="slot-title"><Clock3/> Horarios de demostración</h3>{appointment.date?<div className="time-slots">{slots.map(t=><button className={appointment.time===t?'selected':''} aria-pressed={appointment.time===t} onClick={()=>setAppointment({...appointment,time:t})} key={t}>{t}</button>)}</div>:<div className="empty-slots"><CalendarDays/><p>Elige una fecha para ver horarios.</p></div>}{errors.time&&<p className="field-error" role="alert">{errors.time}</p>}<p className="demo-banner">Estos horarios no representan la agenda real.</p></div>}
export function CustomerForm({customer,setCustomer,errors}){const set=(k,v)=>setCustomer({...customer,[k]:v});return <div><Heading icon={<MessageCircle/>} title="Ya casi terminamos" text="Indica cómo prefieres recibir la confirmación."/><div className="form-grid"><Field label="Nombre completo" value={customer.name} change={v=>set('name',v)} error={errors.customerName} required/><Field label="Teléfono" type="tel" value={customer.phone} change={v=>set('phone',v)} error={errors.phone} required/><Field label="WhatsApp" type="tel" value={customer.whatsapp} change={v=>set('whatsapp',v)} placeholder="Si es diferente"/><Field label="Correo electrónico" type="email" value={customer.email} change={v=>set('email',v)} error={errors.email} required/><label>Método preferido<select value={customer.contactMethod} onChange={e=>set('contactMethod',e.target.value)}><option>WhatsApp</option><option>Llamada</option><option>Correo electrónico</option></select></label></div></div>}
export function BookingReview({pets,appointment,customer,consent,setConsent,errors}){return <div><Heading icon={<Check/>} title="Revisaremos cada detalle" text="Esta solicitud todavía no representa una cita confirmada."/><div className="review-sections"><section><h3>Tus datos</h3><p>{customer.name}<br/>{customer.phone}<br/>{customer.email}<br/>Contacto: {customer.contactMethod}</p></section><section><h3>Momento solicitado</h3><p>{appointment.date}<br/>{appointment.time}</p></section>{pets.map(p=><section key={p.id}><h3>{p.name}</h3><p>{p.species}{p.breed?` · ${p.breed}`:''}</p><ul>{p.services.map(slug=><li key={slug}>{services.find(s=>s.slug===slug)?.name}</li>)}</ul></section>)}</div><label className="consent review-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Entiendo que la solicitud está pendiente de confirmación y autorizo el contacto.</span></label>{errors.consent&&<p className="field-error" role="alert">{errors.consent}</p>}</div>}
export function SelectedServicesSummary({pets,appointment}){return <aside className="booking-summary"><span className="eyebrow">Tu solicitud</span>{pets.map(p=><div className="summary-pet" key={p.id}><h3><PawPrint/>{p.name||'Tu mascota'}</h3><span>{p.services.length} servicios</span>{p.services.map(slug=><small key={slug}>{services.find(s=>s.slug===slug)?.name}</small>)}</div>)}<dl><div><dt>Fecha</dt><dd>{appointment.date||'Por elegir'}</dd></div><div><dt>Hora</dt><dd>{appointment.time||'Por elegir'}</dd></div><div><dt>Precio</dt><dd>Por confirmar</dd></div></dl><p>Disponibilidad y alcance sujetos a confirmación.</p></aside>}
export function MobileBookingSummary({pets,appointment,open,setOpen}){const count=pets.reduce((n,p)=>n+p.services.length,0);return <div className={`mobile-booking-summary ${open?'open':''}`}><button onClick={()=>setOpen(!open)} aria-expanded={open}><span><PawPrint/><b>{pets[0]?.name||'Tu mascota'}</b><small>{count} servicios · {appointment.date||'Sin fecha'}</small></span>{open?<ChevronDown/>:<ChevronUp/>}</button>{open&&<div>{pets.map(p=><p key={p.id}><b>{p.name||'Mascota'}:</b> {p.services.length} servicios</p>)}<span>Precio por confirmar</span></div>}</div>}
export function BookingSuccess({data,onNew}){const [review,setReview]=useState(false),text=`Hola, soy ${data.customer.name}. Quiero consultar la solicitud ${data.request} para ${data.pets.map(p=>`${p.name}: ${p.services.map(slug=>services.find(s=>s.slug===slug)?.name).join(', ')}`).join(' | ')}. Fecha solicitada: ${data.appointment.date} ${data.appointment.time}.`;return <section className="booking-success-page"><div className="success-orbit"><Check/></div><span className="eyebrow">Solicitud {data.request}</span><h1>¡Todo listo! Recibimos la solicitud de {data.pets.map(p=>p.name).join(' y ')}.</h1><p>El equipo revisará los detalles y confirmará la disponibilidad por {data.customer.contactMethod.toLowerCase()}.</p><div className="success-details"><div><span>Mascotas</span><b>{data.pets.map(p=>p.name).join(', ')}</b></div><div><span>Servicios</span><b>{data.pets.reduce((n,p)=>n+p.services.length,0)}</b></div><div><span>Fecha solicitada</span><b>{data.appointment.date} · {data.appointment.time}</b></div></div>{review?<div className="whatsapp-review"><h2>Revisa el mensaje</h2><p>{text}</p><a className="btn btn-primary" href={`https://wa.me/18298931861?text=${encodeURIComponent(text)}`}>Abrir WhatsApp</a><button className="btn btn-ghost" onClick={()=>setReview(false)}>Cancelar</button></div>:<button className="btn btn-primary" onClick={()=>setReview(true)}>Consultar por WhatsApp</button>}<div className="success-links"><Link to="/">Volver al inicio</Link><button onClick={onNew}>Crear otra solicitud</button></div></section>}
function Heading({icon,title,text}){return <div className="panel-heading"><span>{icon}</span><div><h2>{title}</h2><p>{text}</p></div></div>}
function Field({label,value,change,error,type='text',required,placeholder=''}){const id=`f-${label.replace(/\s/g,'-')}`;return <label htmlFor={id}>{label}{required&&' *'}<input id={id} type={type} value={value} onChange={e=>change(e.target.value)} placeholder={placeholder} aria-invalid={!!error}/>{error&&<small className="error" role="alert">{error}</small>}</label>}
function Area({label,value,change}){return <label>{label}<textarea value={value} onChange={e=>change(e.target.value)} placeholder="Opcional"/></label>}
