import { useEffect } from 'react'
import { useLocation } from 'react-router-dom'
import { Camera, CheckCircle2, Images, MapPin, ShieldCheck, Sparkles } from 'lucide-react'
import { posts, services } from './data'

const seo={
 '/':{title:'RealEngo | Grooming, Skin & Spa en Santo Domingo',description:'Grooming, cuidado de la piel, spa y servicios veterinarios para mascotas en Santo Domingo.'},
 '/nosotros':{title:'Nosotros | RealEngo',description:'Conoce el propósito y la filosofía de cuidado responsable de RealEngo.'},
 '/servicios':{title:'Servicios para mascotas | RealEngo',description:'Baños, grooming, consulta veterinaria y cuidado dental para mascotas en Santo Domingo.'},
 '/reservar':{title:'Solicitar una cita | RealEngo',description:'Personaliza el plan de cuidado de una o varias mascotas y solicita fecha y hora.'},
 '/tienda':{title:'Tienda para mascotas | RealEngo',description:'Explora el catálogo oficial de alimentos, higiene, grooming, salud y farmacia veterinaria de RealEngo.'},
 '/blog':{title:'RealenBLOG | RealEngo',description:'Información clara sobre grooming, bienestar y cuidado cotidiano de mascotas.'},
 '/contacto':{title:'Contacto | RealEngo',description:'Comunícate con RealEngo en Santo Domingo por teléfono, correo o redes oficiales.'},
 '/mi-cuenta':{title:'Mi cuenta | RealEngo',description:'Gestiona tus mascotas, solicitudes, favoritos, carrito y datos de contacto.'},
 '/admin':{title:'Administración | RealEngo',description:'Área operativa protegida de RealEngo.'},
}

export function SeoManager(){const {pathname}=useLocation();useEffect(()=>{const slug=pathname.split('/').filter(Boolean).at(-1);const service=pathname.startsWith('/servicios/')?services.find(item=>item.slug===slug):null;const post=pathname.startsWith('/blog/')?posts.find(item=>item.slug===slug):null;const detail=service?{title:`${service.name} | RealEngo`,description:service.short}:post?{title:`${post.title} | RealenBLOG`,description:post.excerpt}:null;const base=seo[pathname]||detail||{title:'RealEngo | Bienestar para mascotas',description:'Cuidado integral para mascotas en Santo Domingo.'};document.title=base.title;const set=(selector,attr,value)=>{let el=document.querySelector(selector);if(!el){el=document.createElement('meta');document.head.appendChild(el)}Object.entries(attr).forEach(([k,v])=>el.setAttribute(k,v));el.setAttribute('content',value)};set('meta[name="description"]',{name:'description'},base.description);set('meta[property="og:title"]',{property:'og:title'},base.title);set('meta[property="og:description"]',{property:'og:description'},base.description);set('meta[property="og:type"]',{property:'og:type'},'website');let canonical=document.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}canonical.href=`https://realengo.do${pathname==='/'?'/inicio/':pathname}`;let schema=document.querySelector('#realengo-schema');if(!schema){schema=document.createElement('script');schema.id='realengo-schema';schema.type='application/ld+json';document.head.appendChild(schema)}schema.textContent=JSON.stringify({'@context':'https://schema.org','@type':['LocalBusiness','VeterinaryCare'],'name':'RealEngo','url':'https://realengo.do/inicio/','telephone':'+1 829 893 1861','email':'info@realengo.com','address':{'@type':'PostalAddress','addressLocality':'Santo Domingo','addressCountry':'DO'},'sameAs':['https://www.instagram.com/realengo.rd/','https://www.tiktok.com/@realengo_rd']})},[pathname]);return null}

export function ScrollReveal(){const {pathname}=useLocation();useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const elements=[...document.querySelectorAll('main .section, main .page-hero, main .detail-hero, main .cta')].filter(el=>!el.classList.contains('immersive-hero'));elements.forEach(el=>el.classList.add('reveal-ready'));const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.08,rootMargin:'0px 0px -45px'});elements.forEach(el=>observer.observe(el));return()=>observer.disconnect()},[pathname]);return null}

export function TrustBand(){return <section className="trust-band" aria-label="Compromisos de RealEngo"><div className="shell">{[[ShieldCheck,'Cuidado responsable','Información clara antes de cada solicitud.'],[Sparkles,'Plan personalizado','Combina servicios para cada mascota.'],[MapPin,'Atención local','RealEngo está en Santo Domingo.']].map(([Icon,title,text])=><div key={title}><Icon/><span><b>{title}</b><small>{text}</small></span></div>)}</div></section>}

export function BeforeAfterReady(){return <section className="section transformation-section" aria-labelledby="transform-title"><div className="shell"><div className="transformation-head"><div><span className="eyebrow">Resultados reales</span><h2 id="transform-title">Transformaciones RealEngo</h2><p>Este espacio está preparado para mostrar fotografías autorizadas del antes y después de cada cuidado.</p></div><Camera aria-hidden="true"/></div><div className="before-after-empty"><div><span>Antes</span><Images/></div><div className="transformation-divider"><CheckCircle2/><span>Contenido verificado</span></div><div><span>Después</span><Images/></div></div><p className="content-status"><ShieldCheck/> No publicamos resultados simulados. Las imágenes aparecerán cuando RealEngo proporcione fotografías locales autorizadas.</p></div></section>}
