import { useEffect, useState } from 'react'
import { Check, ChevronLeft, ChevronRight, ExternalLink, PackageSearch, Search, ShieldCheck, ShoppingBag, SlidersHorizontal } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { api } from './api'

const money=(value,currency='DOP')=>value===null||value===undefined?'Consultar':new Intl.NumberFormat('es-DO',{style:'currency',currency,minimumFractionDigits:2}).format(value)

export function OfficialShop({onAdd}){
 const [categories,setCategories]=useState([]),[products,setProducts]=useState([]),[query,setQuery]=useState(''),[draft,setDraft]=useState(''),[category,setCategory]=useState(null),[sort,setSort]=useState('date-desc'),[page,setPage]=useState(1),[pages,setPages]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[added,setAdded]=useState('')
 useEffect(()=>{api('/api/official/categories').then(data=>setCategories(data.categories)).catch(()=>{})},[])
 useEffect(()=>{let active=true;const [orderby,order]=sort.split('-');setLoading(true);setError('');api(`/api/official/products?page=${page}&perPage=12&orderby=${orderby}&order=${order}${query?`&search=${encodeURIComponent(query)}`:''}${category?`&category=${category}`:''}`).then(data=>{if(active){setProducts(data.products);setPages(data.pages||1);setTotal(data.total)}}).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false}},[page,query,category,sort])
 const chooseCategory=id=>{setCategory(id);setPage(1)},add=product=>{onAdd(product,1);setAdded(product.name);window.setTimeout(()=>setAdded(''),2200)}
 return <><section className="shop-hero"><div className="shell shop-hero-grid"><div><span className="eyebrow">Catálogo oficial RealEngo</span><h1>Todo su cuidado, en una misma estantería.</h1><p>Alimentos, higiene, farmacia veterinaria y productos especializados consultados directamente desde la tienda oficial.</p></div><div className="shop-hero-ticket"><span>Catálogo conectado</span><b>{total||'362'} productos</b><small>Precios e inventario pueden cambiar en RealEngo.</small></div></div></section><main className="section shell official-shop"><section className="category-runway" aria-label="Categorías de productos"><button className={!category?'active':''} onClick={()=>chooseCategory(null)}><span className="category-all"><ShoppingBag/></span><b>Todo</b><small>{total||'362'}</small></button>{categories.map(item=><button key={item.id} className={category===item.id?'active':''} onClick={()=>chooseCategory(item.id)}><span>{item.image&&<img src={item.image} alt="" loading="lazy"/>}</span><b>{item.name}</b><small>{item.count}</small></button>)}</section><div className="shop-toolbar"><form onSubmit={e=>{e.preventDefault();setQuery(draft.trim());setPage(1)}}><Search/><label className="sr-only" htmlFor="official-search">Buscar productos</label><input id="official-search" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Buscar alimento, shampoo, medicamento…"/><button>Buscar</button></form><label className="shop-sort"><SlidersHorizontal/><span className="sr-only">Ordenar productos</span><select value={sort} onChange={e=>{setSort(e.target.value);setPage(1)}}><option value="date-desc">Más recientes</option><option value="title-asc">Nombre A–Z</option><option value="price-asc">Precio menor</option><option value="price-desc">Precio mayor</option><option value="popularity-desc">Más populares</option></select></label></div><div className="shop-result-copy"><span>{loading?'Actualizando catálogo…':`${total} productos encontrados`}</span>{query&&<button onClick={()=>{setQuery('');setDraft('');setPage(1)}}>Limpiar búsqueda “{query}”</button>}</div>{error?<ShopError message={error}/>:loading?<ShopSkeleton/>:products.length?<div className="official-product-grid">{products.map(product=><OfficialProductCard key={product.id} product={product} onAdd={add}/>)}</div>:<ShopEmpty/>}{pages>1&&<nav className="shop-pagination" aria-label="Páginas del catálogo"><button disabled={page===1} onClick={()=>setPage(value=>value-1)}><ChevronLeft/> Anterior</button><span>Página <b>{page}</b> de {pages}</span><button disabled={page===pages} onClick={()=>setPage(value=>value+1)}>Siguiente <ChevronRight/></button></nav>}</main>{added&&<div className="cart-toast" role="status"><Check/><span><b>Agregado al carrito</b>{added}</span><Link to="/carrito">Ver carrito</Link></div>}</>
}

function OfficialProductCard({product,onAdd}){const category=product.categories[0]?.name||'Tienda RealEngo';return <article className="official-product-card"><Link className="official-product-image" to={`/tienda/${product.slug}`}><img src={product.image} alt={product.imageAlt} loading="lazy" decoding="async"/><span className={product.inStock?'in-stock':'out-stock'}>{product.inStock?'Disponible':'Agotado'}</span></Link><div className="official-product-body"><small>{category}</small><h2><Link to={`/tienda/${product.slug}`}>{product.name}</Link></h2><div className="official-price"><b>{money(product.price,product.currency)}</b>{product.salePrice&&product.regularPrice>product.salePrice&&<del>{money(product.regularPrice,product.currency)}</del>}</div><button className="btn btn-primary" disabled={!product.inStock||!product.purchasable} onClick={()=>onAdd(product)}><ShoppingBag/>{product.inStock?'Agregar':'No disponible'}</button></div></article>}

export function OfficialProductDetail({onAdd}){
 const {slug}=useParams(),[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[quantity,setQuantity]=useState(1),[added,setAdded]=useState(false)
 useEffect(()=>{let active=true;setLoading(true);api(`/api/official/products/${slug}`).then(result=>active&&setData(result)).catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));return()=>{active=false}},[slug])
 useEffect(()=>{if(data?.product)document.title=`${data.product.name} | Tienda RealEngo`},[data])
 if(loading)return <section className="section shell"><ShopSkeleton/></section>;if(error||!data)return <section className="section shell"><ShopError message={error||'Producto no encontrado.'}/></section>
 const {product,related}=data,max=product.stock||50,add=()=>{onAdd(product,quantity);setAdded(true);window.setTimeout(()=>setAdded(false),2200)}
 return <><main className="section shell official-detail"><Link className="back" to="/tienda"><ChevronLeft/> Volver a la tienda</Link><div className="official-detail-grid"><div className="official-detail-image"><img src={product.image} alt={product.imageAlt}/><span>{product.inStock?'Disponible en catálogo oficial':'Agotado'}</span></div><div className="official-detail-copy"><span className="eyebrow">{product.categories.map(item=>item.name).join(' · ')||'Producto RealEngo'}</span><h1>{product.name}</h1><div className="official-detail-price">{money(product.price,product.currency)}</div><p>{product.summary||'Consulta disponibilidad, uso recomendado y cualquier indicación relevante directamente con el equipo de RealEngo.'}</p><dl><div><dt>SKU</dt><dd>{product.sku||'Por confirmar'}</dd></div><div><dt>Inventario</dt><dd>{product.stock!==null?`${product.stock} disponibles`:product.inStock?'Disponible':'Agotado'}</dd></div><div><dt>Origen</dt><dd>Catálogo oficial RealEngo</dd></div></dl><div className="official-buy"><label>Cantidad<input type="number" min="1" max={max} value={quantity} onChange={e=>setQuantity(Math.max(1,Math.min(max,Number(e.target.value)||1)))}/></label><button className="btn btn-primary" disabled={!product.inStock||!product.purchasable} onClick={add}><ShoppingBag/> Agregar al carrito</button></div><div className="official-source-note"><ShieldCheck/><span>Precio e inventario consultados desde realengo.do. La disponibilidad final se confirma al procesar el pedido.</span></div><a className="text-link" href={product.officialUrl} target="_blank" rel="noopener noreferrer">Ver ficha en la tienda oficial <ExternalLink/></a></div></div>{related.length>0&&<section className="related-products"><div><span className="eyebrow">También puede necesitar</span><h2>Productos relacionados</h2></div><div className="official-product-grid">{related.slice(0,4).map(item=><OfficialProductCard key={item.id} product={item} onAdd={onAdd}/>)}</div></section>}</main>{added&&<div className="cart-toast" role="status"><Check/><span><b>Agregado al carrito</b>{quantity} × {product.name}</span><Link to="/carrito">Ver carrito</Link></div>}</>
}

function ShopSkeleton(){return <div className="shop-skeleton" aria-label="Cargando productos">{Array.from({length:8},(_,i)=><i key={i}/>)}</div>}
function ShopError({message}){return <div className="shop-error" role="alert"><PackageSearch/><h2>No pudimos cargar la tienda</h2><p>{message}</p><button className="btn btn-primary" onClick={()=>window.location.reload()}>Intentar de nuevo</button></div>}
function ShopEmpty(){return <div className="shop-error"><PackageSearch/><h2>No encontramos productos</h2><p>Prueba otra búsqueda o vuelve a ver todas las categorías.</p></div>}
